import { ColorModeScript } from '@chakra-ui/react';

import { Providers } from './providers';
import { theme } from './theme';

import './global.css';

export const metadata = {
  title: 'Welcome to recipes-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
